/* plugin-interface.c generated by valac 0.40.25, the Vala compiler
 * generated from plugin-interface.vala, do not modify */



#include <glib.h>
#include <glib-object.h>


#define TYPE_TEST_PLUGIN (test_plugin_get_type ())
#define TEST_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEST_PLUGIN, TestPlugin))
#define IS_TEST_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEST_PLUGIN))
#define TEST_PLUGIN_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_TEST_PLUGIN, TestPluginIface))

typedef struct _TestPlugin TestPlugin;
typedef struct _TestPluginIface TestPluginIface;

struct _TestPluginIface {
	GTypeInterface parent_iface;
	void (*hello) (TestPlugin* self);
};



GType test_plugin_get_type (void) G_GNUC_CONST;
void test_plugin_hello (TestPlugin* self);


void
test_plugin_hello (TestPlugin* self)
{
	g_return_if_fail (self != NULL);
	TEST_PLUGIN_GET_INTERFACE (self)->hello (self);
}


static void
test_plugin_default_init (TestPluginIface * iface)
{
}


GType
test_plugin_get_type (void)
{
	static volatile gsize test_plugin_type_id__volatile = 0;
	if (g_once_init_enter (&test_plugin_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TestPluginIface), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) test_plugin_default_init, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType test_plugin_type_id;
		test_plugin_type_id = g_type_register_static (G_TYPE_INTERFACE, "TestPlugin", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (test_plugin_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&test_plugin_type_id__volatile, test_plugin_type_id);
	}
	return test_plugin_type_id__volatile;
}



