/* weather.c generated by valac 0.40.25, the Vala compiler
 * generated from weather.vala, do not modify */

/*
valac --pkg gmodule-2.0 -C weather.vala plugin-interface.vala
gcc -shared -fPIC $(pkg-config --cflags --libs glib-2.0 gmodule-2.0) -o libweather.so weather.c
*/


#include <glib.h>
#include <glib-object.h>
#include <stdio.h>
#include <gmodule.h>


#define TYPE_TEST_PLUGIN (test_plugin_get_type ())
#define TEST_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEST_PLUGIN, TestPlugin))
#define IS_TEST_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEST_PLUGIN))
#define TEST_PLUGIN_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_TEST_PLUGIN, TestPluginIface))

typedef struct _TestPlugin TestPlugin;
typedef struct _TestPluginIface TestPluginIface;

#define TYPE_WEATHER_PLUGIN (weather_plugin_get_type ())
#define WEATHER_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_WEATHER_PLUGIN, WeatherPlugin))
#define WEATHER_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_WEATHER_PLUGIN, WeatherPluginClass))
#define IS_WEATHER_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_WEATHER_PLUGIN))
#define IS_WEATHER_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_WEATHER_PLUGIN))
#define WEATHER_PLUGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_WEATHER_PLUGIN, WeatherPluginClass))

typedef struct _WeatherPlugin WeatherPlugin;
typedef struct _WeatherPluginClass WeatherPluginClass;
typedef struct _WeatherPluginPrivate WeatherPluginPrivate;
enum  {
	WEATHER_PLUGIN_0_PROPERTY,
	WEATHER_PLUGIN_NUM_PROPERTIES
};
static GParamSpec* weather_plugin_properties[WEATHER_PLUGIN_NUM_PROPERTIES];

struct _TestPluginIface {
	GTypeInterface parent_iface;
	void (*hello) (TestPlugin* self);
};

struct _WeatherPlugin {
	GObject parent_instance;
	WeatherPluginPrivate * priv;
};

struct _WeatherPluginClass {
	GObjectClass parent_class;
};


static gpointer weather_plugin_parent_class = NULL;
static TestPluginIface * weather_plugin_test_plugin_parent_iface = NULL;

GType test_plugin_get_type (void) G_GNUC_CONST;
GType weather_plugin_get_type (void) G_GNUC_CONST;
static void weather_plugin_real_hello (TestPlugin* base);
WeatherPlugin* weather_plugin_new (void);
WeatherPlugin* weather_plugin_construct (GType object_type);
void test_plugin_hello (TestPlugin* self);
GType register_plugin (GModule* module);


static void
weather_plugin_real_hello (TestPlugin* base)
{
	WeatherPlugin * self;
	FILE* _tmp0_;
	self = (WeatherPlugin*) base;
	_tmp0_ = stdout;
	fprintf (_tmp0_, "Hello weather!\n");
}


WeatherPlugin*
weather_plugin_construct (GType object_type)
{
	WeatherPlugin * self = NULL;
	self = (WeatherPlugin*) g_object_new (object_type, NULL);
	return self;
}


WeatherPlugin*
weather_plugin_new (void)
{
	return weather_plugin_construct (TYPE_WEATHER_PLUGIN);
}


static void
weather_plugin_class_init (WeatherPluginClass * klass)
{
	weather_plugin_parent_class = g_type_class_peek_parent (klass);
}


static void
weather_plugin_test_plugin_interface_init (TestPluginIface * iface)
{
	weather_plugin_test_plugin_parent_iface = g_type_interface_peek_parent (iface);
	iface->hello = (void (*) (TestPlugin*)) weather_plugin_real_hello;
}


static void
weather_plugin_instance_init (WeatherPlugin * self)
{
}


GType
weather_plugin_get_type (void)
{
	static volatile gsize weather_plugin_type_id__volatile = 0;
	if (g_once_init_enter (&weather_plugin_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WeatherPluginClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) weather_plugin_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WeatherPlugin), 0, (GInstanceInitFunc) weather_plugin_instance_init, NULL };
		static const GInterfaceInfo test_plugin_info = { (GInterfaceInitFunc) weather_plugin_test_plugin_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType weather_plugin_type_id;
		weather_plugin_type_id = g_type_register_static (G_TYPE_OBJECT, "WeatherPlugin", &g_define_type_info, 0);
		g_type_add_interface_static (weather_plugin_type_id, TYPE_TEST_PLUGIN, &test_plugin_info);
		g_once_init_leave (&weather_plugin_type_id__volatile, weather_plugin_type_id);
	}
	return weather_plugin_type_id__volatile;
}


GType
register_plugin (GModule* module)
{
	GType result = 0UL;
	g_return_val_if_fail (module != NULL, 0UL);
	result = TYPE_WEATHER_PLUGIN;
	return result;
}



